// The canonical Checkpoint SDK contract — single source of truth for every
// wrapper's conformance fixture.
//
// This module is COMPILE-PINNED against the real surface (definitions.ts,
// index.ts, api.ts): every array below is mutually-assignable with the type it
// mirrors, so renaming/adding/removing a method, field, or wire value is a tsc
// error HERE before it can drift anywhere else. The machine-readable export of
// this module is contract/checkpoint-contract.json (generated by
// scripts/generate-contract.mjs, freshness-asserted by test/contract.test.mjs,
// shipped in the npm tarball so wrapper test suites can import it).
//
// Wrapper fixtures (RN/Expo/Cordova/NativeScript TS specs, Flutter Dart, MAUI
// C#, KMP Kotlin) are cross-checked against the JSON in CI by
// scripts/check-contract-sync.mjs.

import type {
  NativeGeofencePlugin,
  NativeDiagnostics,
  RegionEvent,
  TrackingMode,
} from "./definitions.js";
import type { OutageReason } from "./api.js";

/** Layer-1 raw native plugin method names (definitions.ts NativeGeofencePlugin). */
export const NATIVE_METHODS = [
  "configure",
  "requestAlwaysAuthorization",
  "requestNotificationAuthorization",
  "requestBatteryExemption",
  "openAppSettings",
  "addFence",
  "clearFences",
  "setTrackingMode",
  "getTrackingMode",
  "getDiagnostics",
  "addListener",
] as const;

/** Layer-2 ergonomic facade method names (index.ts Checkpoint). */
export const FACADE_METHODS = [
  "init",
  "isConfigured",
  "setTrackingMode",
  "getTrackingMode",
  "getTrackingDirective",
  "setDeviceTrackingMode",
] as const;

/** TrackingMode wire values (the exact strings the native cores + /v1 use). */
export const TRACKING_MODE_WIRE = ["geofence", "always", "off"] as const;

/** RegionEvent.type wire values (stray_stream_stopped: regionId "" + last-fix semantics). */
export const REGION_EVENT_TYPES = ["enter", "exit", "update", "stray_stream_stopped"] as const;

/** RegionEvent field set. */
export const REGION_EVENT_FIELDS = [
  "type",
  "regionId",
  "latitude",
  "longitude",
  "accuracy",
  "timestamp",
] as const;

/** NativeDiagnostics field set (required + optional). */
export const NATIVE_DIAGNOSTICS_FIELDS = [
  "authStatus",
  "monitoredCount",
  "monitoredIds",
  "configured",
  "subjectExternalId",
  "baseUrl",
  "fences",
  "armedFenceCount",
  "locationServicesEnabled",
  "ignoringBatteryOptimizations",
  "mode",
  "streaming",
  "lastStreamFixAt",
  "streamNow",
  "slcMonitoring",
  "maxStrayStreamS",
  "lastStrayStreamStopAt",
] as const;

/** configure() option keys (incl. maxStrayStreamS). */
export const CONFIGURE_OPTION_KEYS = [
  "baseUrl",
  "anonKey",
  "publishableKey",
  "subjectExternalId",
  "deviceId",
  "trackingMode",
  "streamNow",
  "minIntervalS",
  "maxStrayStreamS",
] as const;

/**
 * The get_device_tracking_directive RPC body keys — all THREE always sent (R8:
 * never drop one; trailing params default NULL server-side). Data-only pin: the
 * body is built in api.ts getTrackingDirective and asserted by wire tests.
 */
export const DIRECTIVE_RPC_KEYS = ["p_subject", "p_app_id", "p_device_ref"] as const;

/** OutageReason wire values (api.ts — the closed reason enum /v1/outages accepts). */
export const OUTAGE_REASONS = [
  "permission_revoked",
  "permission_while_in_use_only",
  "location_services_off",
  "background_permission_denied",
  "battery_saver_or_doze",
  "force_quit_recovery",
  "airplane_mode",
  "connectivity_lost",
  "gps_signal_lost",
  "mock_location_detected",
  "tracking_disabled_by_user",
  "presence_inferred_stale",
] as const;

/**
 * Ingest `source` values THIS SDK emits (server-side the field is open-ended /
 * forward-compatible — see v1-ingest FixSource): the JS foreground stream posts
 * "foreground_stream" (presence.ts ingestFix); the native cores post
 * "native_region_wake" (one-shot crossing ping) and "continuous_stream"
 * (fine stream) — GeofenceManager.swift / GeofenceStore.java. Data-only pin.
 */
export const INGEST_SOURCES = [
  "foreground_stream",
  "native_region_wake",
  "continuous_stream",
] as const;

// ── Compile-level pins ────────────────────────────────────────────────────────
// `true` is only assignable when the two string unions are mutually assignable,
// i.e. the fixture array covers the type exactly (both directions).

type MutuallyAssignable<A extends string, B extends string> = [A] extends [B]
  ? [B] extends [A]
    ? true
    : false
  : false;

const _pinNativeMethods: MutuallyAssignable<
  (typeof NATIVE_METHODS)[number],
  keyof NativeGeofencePlugin
> = true;
const _pinFacadeMethods: MutuallyAssignable<
  (typeof FACADE_METHODS)[number],
  keyof (typeof import("./index.js"))["Checkpoint"]
> = true;
const _pinTrackingMode: MutuallyAssignable<(typeof TRACKING_MODE_WIRE)[number], TrackingMode> =
  true;
const _pinRegionEventTypes: MutuallyAssignable<
  (typeof REGION_EVENT_TYPES)[number],
  RegionEvent["type"]
> = true;
const _pinRegionEventFields: MutuallyAssignable<
  (typeof REGION_EVENT_FIELDS)[number],
  keyof RegionEvent
> = true;
const _pinDiagnosticsFields: MutuallyAssignable<
  (typeof NATIVE_DIAGNOSTICS_FIELDS)[number],
  keyof NativeDiagnostics
> = true;
const _pinConfigureKeys: MutuallyAssignable<
  (typeof CONFIGURE_OPTION_KEYS)[number],
  keyof Parameters<NativeGeofencePlugin["configure"]>[0]
> = true;
const _pinOutageReasons: MutuallyAssignable<(typeof OUTAGE_REASONS)[number], OutageReason> = true;
void _pinNativeMethods;
void _pinFacadeMethods;
void _pinTrackingMode;
void _pinRegionEventTypes;
void _pinRegionEventFields;
void _pinDiagnosticsFields;
void _pinConfigureKeys;
void _pinOutageReasons;

/** The full canonical contract, shape-identical to contract/checkpoint-contract.json (minus the version stamp). */
export const CHECKPOINT_CONTRACT = {
  nativeMethods: NATIVE_METHODS,
  facadeMethods: FACADE_METHODS,
  trackingModeWire: TRACKING_MODE_WIRE,
  regionEventTypes: REGION_EVENT_TYPES,
  regionEventFields: REGION_EVENT_FIELDS,
  nativeDiagnosticsFields: NATIVE_DIAGNOSTICS_FIELDS,
  configureOptionKeys: CONFIGURE_OPTION_KEYS,
  directiveRpcKeys: DIRECTIVE_RPC_KEYS,
  outageReasons: OUTAGE_REASONS,
  ingestSources: INGEST_SOURCES,
} as const;
